version: '3'
services:
  reddrec:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - rqworker
      - datadeps
    volumes:
      - .:/app
    environment:
      - 'PYTHONUNBUFFERED=true'
      - 'FLASK_APP=reddrec'
      - 'FLASK_RUN_HOST=0.0.0.0'
      - 'FLASK_ENV=development'
      - reddrec_praw_client_id
      - reddrec_praw_client_secret
      - reddrec_praw_username
      - reddrec_praw_password
      - reddrec_praw_user_agent
    command: bash -c 'flask run'
  redis:
    image: redis:5.0.8
  rcli:
    image: redis:5.0.8
    depends_on:
      - redis
    command: 'redis-cli -h redis'
  rqworker:
    build: .
    depends_on:
      - redis
      - datadeps
    volumes:
      - .:/app
    command: bash -c 'rq worker --url redis://:@redis:6379'
    environment:
      - reddrec_praw_client_id
      - reddrec_praw_client_secret
      - reddrec_praw_username
      - reddrec_praw_password
      - reddrec_praw_user_agent
  test:
    build: .
    depends_on:
      - datadeps
    volumes:
      - .:/app
    command: bash -c 'python -m pytest tests/'
    environment:
      - prawtest_client_id
      - prawtest_client_secret
      - prawtest_username
      - prawtest_password
      - prawtest_user_agent
  refresh_datadeps:
    build: .
    volumes:
      - .:/app
    command: 'python datadeps -retry'
  datadeps:
    build: .
    volumes:
      - .:/app
    command: 'python datadeps'
