version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Python tests
          command: |
            pip install -r requirements.txt
            python datadeps
            python -m pytest tests/
workflows:
  main:
    jobs:
      - build-and-test
