version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Python tests
          command: |
            pip install -r requirements.txt
            python datadeps
            python -m pytest tests/
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
workflows:
  main:
    jobs:
      - build-and-test
