version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - ./src:/app
    environment:
      FLASK_APP: 'main/app.py'
      FLASK_RUN_HOST: '0.0.0.0'
      FLASK_ENV: 'development'
    command: 'flask run'
  redis:
    image: redis:5.0.8
  rcli:
    image: redis:5.0.8
    depends_on:
      - redis
    command: 'redis-cli -h redis'
  rqworker:
    build: .
    depends_on:
      - app
      - redis
    volumes:
      - ./src:/app
    command: 'rq worker --url redis://:@redis:6379'
