version: '3'
services:
  reddrec:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - rqworker
    volumes:
      - .:/app
    environment:
      PYTHONUNBUFFERED: 'true'
      FLASK_APP: 'reddrec'
      FLASK_RUN_HOST: '0.0.0.0'
      FLASK_ENV: 'development'
    command: 'flask run'
  redis:
    image: redis:5.0.8
  rcli:
    image: redis:5.0.8
    depends_on:
      - redis
    command: 'redis-cli -h redis'
  rqworker:
    build: .
    depends_on:
      - redis
    volumes:
      - .:/app
    command: 'rq worker --url redis://:@redis:6379'
  test:
    build: .
    volumes:
      - .:/app
    depends_on:
      - reddrec
    command: 'python -m pytest'
